import { TIngredientWithUniqueId } from "../types/ingredients-types";

export const mockedIngredientsWithNanoId: Array<TIngredientWithUniqueId> = [
  {
    calories: 420,
    carbohydrates: 53,
    fat: 24,
    image: "https://code.s3.yandex.net/react/code/bun-02.png",
    image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
    image_mobile: "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
    name: "Краторная булка N-200i",
    price: 1255,
    proteins: 80,
    type: "bun",
    __v: 0,
    _id: "643d69a5c3f7b9001cfa093c",
    qty: 1,
    nanoid: "DCuh1pE_3cIc4ARqdhgbR",
  },
  {
    calories: 4242,
    carbohydrates: 242,
    fat: 142,
    image: "https://code.s3.yandex.net/react/code/meat-01.png",
    image_large: "https://code.s3.yandex.net/react/code/meat-01-large.png",
    image_mobile: "https://code.s3.yandex.net/react/code/meat-01-mobile.png",
    name: "Биокотлета из марсианской Магнолии",
    price: 424,
    proteins: 420,
    type: "main",
    __v: 0,
    _id: "643d69a5c3f7b9001cfa0941",
    qty: 1,
    nanoid: "mYKU0mKsTujDPRtYnNAKR",
  },
  {
    calories: 643,
    carbohydrates: 85,
    fat: 26,
    image: "https://code.s3.yandex.net/react/code/meat-03.png",
    image_large: "https://code.s3.yandex.net/react/code/meat-03-large.png",
    image_mobile: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
    name: "Филе Люминесцентного тетраодонтимформа",
    price: 988,
    proteins: 44,
    type: "main",
    __v: 0,
    _id: "643d69a5c3f7b9001cfa093e",
    qty: 1,
    nanoid: "iW4FUZtMCNjXpcFDRwQD3",
  },
  {
    calories: 30,
    carbohydrates: 40,
    fat: 20,
    image: "https://code.s3.yandex.net/react/code/sauce-02.png",
    image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
    image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
    name: "Соус Spicy-X",
    price: 90,
    proteins: 30,
    type: "sauce",
    __v: 0,
    _id: "643d69a5c3f7b9001cfa0942",
    qty: 1,
    nanoid: "qviXsytzyeuPLjSjJDAoe",
  },
  {
    calories: 643,
    carbohydrates: 85,
    fat: 26,
    image: "https://code.s3.yandex.net/react/code/bun-01.png",
    image_large: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
    image_mobile: "https://code.s3.yandex.net/react/code/bun-01-large.png",
    name: "Флюоресцентная булка R2-D3",
    price: 988,
    proteins: 44,
    type: "bun",
    __v: 0,
    _id: "643d69a5c3f7b9001cfa093d",
    qty: 1,
    nanoid: "MqDGmBw23kETR2yHKqn9p",
  },
];
