export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
export const INGREDIENTS_COUNTER_INCREASE = "INGREDIENTS_COUNTER_INCREASE";
export const INGREDIENTS_COUNTER_DECREASE = "INGREDIENTS_COUNTER_DECREASE";
export const CHANGE_BUN = "CHANGE_BUN";
