export const GET_ORDER_ID_REQUEST = "GET_ORDER_ID_REQUEST";
export const GET_ORDER_ID_SUCCESS = "GET_ORDER_ID_SUCCESS";
export const GET_ORDER_ID_FAILED = "GET_ORDER_ID_FAILED";

// export const SET_INGREDIENTS_ID = "SET_INGREDIENTS_ID";
